openapi: "3.1.0"

info:
  title: AlgaShop - Ordering
  version: "1.0"

servers:
  - description: Development
    url: "http://localhost:8080"
  - description: Production
    url: "https://api.algashop.com"

paths:
  /test:
    get:
      responses:
        '200':
          description: OK
